export const moviesData = [
    {
      id: Math.random(),
      image:'https://sportshub.cbsistatic.com/i/2021/12/18/4a3fdbcc-7ea5-4ca8-b2ac-946e1e893dba/bleach-anime.png?auto=webp&width=822&height=1152&crop=0.714:1,smart',
      rating: 5,
      name: "Bleach: 100-Year Blood War",
      date: '2022',
      type: 'Action | Adventure | Anime',
      description:"The peace is suddenly broken when warning sirens blare through the Soul Society. Residents are disappearing without a trace and nobody knows who's behind it. Meanwhile, a darkness is approaching Ichigo and his friends in Karakura Town.",
    },
    {
      id: Math.random(),
      image:'https://m.media-amazon.com/images/I/71aoeOhdNnL._AC_SL1000_.jpg',
      rating: 4.5,
      name: 'Hunter X Hunter',
      date: '2011',
      type: 'Action | Adventure | Anime',
      description:'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks out his father, who left him when he was younger.',
    },
    {
      id: Math.random(),
      image:'https://i.ebayimg.com/images/g/~U8AAOSwspBg7ULt/s-l500.jpg',
      rating: 4,
      name: 'Chainsaw Man',
      date: '2022',
      type: 'Action | Adventure | Anime',
      description:'Following a betrayal, a young man left for the dead is reborn as a powerful devil-human hybrid after merging with his pet devil and is soon enlisted into an organization dedicated to hunting devils.',
    },
    {
      id: Math.random(),
      image:'https://m.media-amazon.com/images/I/81W03BksEjL._AC_SL1500_.jpg',
      rating: 5,
      name: 'One Piece',
      date: '1999',
      type: 'Action | Adventure | Anime',
      description:'Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger. The famous mystery treasure named "One Piece".',
    },
    {
      id: Math.random(),
      image:'https://m.media-amazon.com/images/M/MV5BMWE4OWE0NmMtYjlmOC00NGE1LWJiNDItNDgxNzVjYzViMGQ3XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg',
      rating: 4.5,
      name: 'Vinland Saga',
      date: '2019',
      type: 'Action | Adventure | Anime',
      description:'Thorfinn pursues a journey with his father killer in order to take revenge and end his life in a duel as an honorable warrior and pay his father a homage.',
    },
    {
      id: Math.random(),
      image:'https://i.pinimg.com/originals/71/73/59/71735901596a554a253359909bb39266.jpg',
      rating: 4.5,
      name: 'Naruto: Shippuden',
      date: '2007',
      type: 'Action | Adventure | Anime',
      description:"Naruto Uzumaki, is a loud, hyperactive, adolescent ninja who constantly searches for approval and recognition, as well as to become Hokage, who is acknowledged as the leader and strongest of all ninja in the village.",
    },
    {
      id: Math.random(),
      image:"https://i.pinimg.com/originals/b3/0d/6d/b30d6d12155c286edf7aeb7ece9c283d.jpg",
      rating: 4,
      name: "Monster",
      date: "2004",
      type: " Anime | Crime | Drama  ",
      description:"Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government."
    }
  ];